/* PantryPilot — local data: recipes + seed pantry.
   Ingredients use canonical lowercase names so tools can match pantry items reliably.
   PORTIONS gives the amount each recipe consumes per 2 servings (the unit the
   shopping list and pantry deduction use). */

const RECIPE_DB = [
  { id: "r01", name: "Garlicky Spinach Pasta", emoji: "🍝", minutes: 25, tags: ["vegetarian","comfort"],
    ingredients: ["spinach","pasta","garlic","olive oil","parmesan"], uses: "boil, wilt, toss",
    steps: ["Boil the pasta in salted water until al dente; save a cup of pasta water.", "Sizzle sliced garlic in olive oil until golden, then wilt in the spinach.", "Toss pasta with the spinach, pasta water and grated parmesan. Serve."] },
  { id: "r02", name: "Chicken Stir-Fry", emoji: "🥘", minutes: 30, tags: ["high-protein","weeknight"],
    ingredients: ["chicken breast","bell pepper","soy sauce","garlic","rice","carrot"], uses: "stir-fry",
    steps: ["Cook the rice and keep warm.", "Sear chicken strips over high heat; set aside.", "Stir-fry bell pepper, carrot and garlic, return the chicken, splash soy sauce and serve over rice."] },
  { id: "r03", name: "Miso Soup with Tofu", emoji: "🍜", minutes: 15, tags: ["vegetarian","light"],
    ingredients: ["tofu","miso paste","scallions","wakame","dashi"], uses: "simmer",
    steps: ["Simmer dashi with wakame for 5 minutes.", "Whisk in miso paste off the boil; add cubed tofu.", "Ladle into bowls and top with scallions."] },
  { id: "r04", name: "Shakshuka", emoji: "🍳", minutes: 35, tags: ["vegetarian","brunch"],
    ingredients: ["eggs","tomato","bell pepper","onion","cumin","olive oil"], uses: "poach in sauce",
    steps: ["Soften onion and bell pepper in olive oil with cumin.", "Add chopped tomato and simmer into a thick sauce.", "Crack in the eggs, cover, and poach 6-8 minutes."] },
  { id: "r05", name: "Salmon & Roast Veggies", emoji: "🐟", minutes: 40, tags: ["high-protein","omega-3"],
    ingredients: ["salmon","potato","broccoli","olive oil","lemon"], uses: "roast",
    steps: ["Roast potato wedges and broccoli in olive oil at 200°C for 20 minutes.", "Add salmon fillets, season, and roast 12 more minutes.", "Finish with lemon juice and serve."] },
  { id: "r06", name: "Mushroom Risotto", emoji: "🍚", minutes: 45, tags: ["vegetarian","comfort"],
    ingredients: ["mushrooms","arborio rice","onion","parmesan","butter"], uses: "slow stir",
    steps: ["Brown the mushrooms in butter; set aside.", "Sweat onion, add arborio rice, then water/stock a ladle at a time, stirring 20 minutes.", "Fold in mushrooms and parmesan. Rest 2 minutes."] },
  { id: "r07", name: "Black Bean Tacos", emoji: "🌮", minutes: 20, tags: ["vegetarian","budget"],
    ingredients: ["black beans","tortillas","onion","avocado","lime","cumin"], uses: "warm & fold",
    steps: ["Warm black beans with diced onion, cumin and a splash of water.", "Char the tortillas directly over the flame.", "Fill with beans, avocado slices and lime."] },
  { id: "r08", name: "Greek Salad Bowl", emoji: "🥗", minutes: 15, tags: ["vegetarian","no-cook"],
    ingredients: ["cucumber","tomato","feta","red onion","olive oil","olives"], uses: "toss",
    steps: ["Chop cucumber, tomato and red onion into chunks.", "Toss with olives, olive oil and a pinch of salt.", "Crumble feta over the top and serve."] },
  { id: "r09", name: "Beef & Broccoli Noodles", emoji: "🍖", minutes: 30, tags: ["high-protein"],
    ingredients: ["beef strips","broccoli","noodles","soy sauce","garlic","ginger"], uses: "stir-fry",
    steps: ["Boil the noodles; blanch the broccoli.", "Sear beef strips with garlic and ginger over fierce heat.", "Toss everything with soy sauce and serve."] },
  { id: "r10", name: "Pumpkin Soup", emoji: "🎃", minutes: 40, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["pumpkin","onion","carrot","vegetable stock","cream"], uses: "blend & simmer",
    steps: ["Sweat onion and carrot, add pumpkin chunks and stock.", "Simmer 25 minutes until completely soft.", "Blend smooth, swirl in cream and serve."] },
  { id: "r11", name: "Egg Fried Rice", emoji: "🍙", minutes: 15, tags: ["budget","weeknight"],
    ingredients: ["eggs","rice","scallions","soy sauce","carrot","peas"], uses: "wok",
    steps: ["Scramble the eggs in a hot wok; set aside.", "Fry diced carrot, peas and day-old rice until toasty.", "Return the egg, season with soy sauce, top with scallions."] },
  { id: "r12", name: "Caprese Sandwich", emoji: "🥪", minutes: 10, tags: ["vegetarian","no-cook"],
    ingredients: ["mozzarella","tomato","basil","bread","olive oil"], uses: "stack",
    steps: ["Toast the bread and drizzle with olive oil.", "Layer mozzarella, tomato slices and basil.", "Season, press, and halve."] },
  { id: "r13", name: "Lentil Dahl", emoji: "🍛", minutes: 45, tags: ["vegan","budget","freezer-friendly"],
    ingredients: ["red lentils","onion","tomato","ginger","cumin","coconut milk"], uses: "simmer",
    steps: ["Sweat onion, ginger and cumin until fragrant.", "Add lentils, tomato and water; simmer 30 minutes.", "Stir in coconut milk and serve over rice."] },
  { id: "r14", name: "Roast Chicken & Roots", emoji: "🍗", minutes: 70, tags: ["family","high-protein"],
    ingredients: ["whole chicken","potato","carrot","onion","rosemary","olive oil"], uses: "roast",
    steps: ["Rub the chicken with olive oil, salt and rosemary.", "Surround with potato, carrot and onion chunks.", "Roast at 190°C about 60 minutes; rest 10 before carving."] },
  { id: "r15", name: "Shrimp Garlic Noodles", emoji: "🍤", minutes: 20, tags: ["high-protein","weeknight"],
    ingredients: ["shrimp","noodles","garlic","butter","scallions","lemon"], uses: "sauté",
    steps: ["Boil the noodles.", "Sauté garlic in butter, add shrimp and cook until pink.", "Toss with noodles, lemon juice and scallions."] },
  { id: "r16", name: "Veggie Frittata", emoji: "🥚", minutes: 30, tags: ["vegetarian","clean-out-fridge"],
    ingredients: ["eggs","zucchini","bell pepper","onion","cheese"], uses: "bake",
    steps: ["Soften zucchini, bell pepper and onion in an oven-safe pan.", "Pour over beaten eggs with cheese.", "Bake at 180°C 15 minutes until set."] },
  { id: "r17", name: "Tomato Basil Bruschetta", emoji: "🍅", minutes: 15, tags: ["vegetarian","snack"],
    ingredients: ["tomato","basil","bread","garlic","olive oil"], uses: "toast & top",
    steps: ["Dice tomato with basil, olive oil and salt.", "Toast bread slices and rub with garlic.", "Spoon the tomato mix on top and serve."] },
  { id: "r18", name: "Pork Chops & Apples", emoji: "🥩", minutes: 35, tags: ["family"],
    ingredients: ["pork chops","apple","onion","butter","thyme"], uses: "pan-sear",
    steps: ["Sear pork chops in butter until golden; set aside.", "Soften onion and apple slices with thyme in the same pan.", "Return the chops, cover, and finish 10 minutes."] },
  { id: "r19", name: "Chickpea Curry", emoji: "🍲", minutes: 35, tags: ["vegan","budget","freezer-friendly"],
    ingredients: ["chickpeas","onion","tomato","curry powder","coconut milk","spinach"], uses: "simmer",
    steps: ["Sweat onion with curry powder until fragrant.", "Add chickpeas, tomato and coconut milk; simmer 20 minutes.", "Wilt in the spinach and serve over rice."] },
  { id: "r20", name: "Zucchini Fritters", emoji: "🥒", minutes: 25, tags: ["vegetarian","clean-out-fridge"],
    ingredients: ["zucchini","eggs","flour","feta","dill"], uses: "pan-fry",
    steps: ["Grate zucchini, salt, squeeze dry.", "Mix with eggs, flour, feta and dill.", "Pan-fry spoonfuls until crisp and golden."] },
  { id: "r21", name: "Minestrone", emoji: "🥣", minutes: 45, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["carrot","celery","tomato","beans","pasta","vegetable stock"], uses: "simmer",
    steps: ["Sweat carrot and celery, add tomato and stock.", "Simmer 20 minutes, add beans and small pasta.", "Cook until pasta is tender; serve with olive oil."] },
  { id: "r22", name: "Fish Tacos with Slaw", emoji: "🐟", minutes: 30, tags: ["weeknight"],
    ingredients: ["white fish","tortillas","cabbage","lime","avocado","yogurt"], uses: "sear & wrap",
    steps: ["Slice cabbage and dress with lime and salt for slaw.", "Sear seasoned fish until flaky.", "Wrap in warm tortillas with slaw, avocado and yogurt."] },
  { id: "r23", name: "Mushroom Toast", emoji: "🍄", minutes: 15, tags: ["vegetarian","snack"],
    ingredients: ["mushrooms","bread","butter","garlic","thyme"], uses: "sauté & pile",
    steps: ["Sauté mushrooms hard in butter with garlic and thyme.", "Toast thick bread slices.", "Pile mushrooms on toast and serve."] },
  { id: "r24", name: "Sheet-Pan Sausage & Peppers", emoji: "🌭", minutes: 40, tags: ["family","one-pan"],
    ingredients: ["sausages","bell pepper","onion","potato","olive oil"], uses: "roast",
    steps: ["Toss sausages, peppers, onion and potato in olive oil on a sheet pan.", "Roast at 200°C 30 minutes, turning once.", "Serve straight from the pan."] },
  { id: "r25", name: "Tofu Veggie Bowl", emoji: "🥡", minutes: 25, tags: ["vegan","meal-prep"],
    ingredients: ["tofu","rice","broccoli","carrot","soy sauce","sesame seeds"], uses: "assemble",
    steps: ["Crisp tofu cubes in a hot pan; steam the broccoli.", "Cook the rice.", "Assemble bowls, drizzle soy sauce, scatter sesame seeds."] },
  { id: "r26", name: "Banana Oat Pancakes", emoji: "🥞", minutes: 20, tags: ["breakfast","vegetarian"],
    ingredients: ["banana","oats","eggs","yogurt","honey"], uses: "blend & griddle",
    steps: ["Blend banana, oats and eggs into a batter.", "Griddle small pancakes 2 minutes per side.", "Stack with yogurt and honey."] },
  { id: "r27", name: "Cauliflower Cheese Bake", emoji: "🧀", minutes: 50, tags: ["vegetarian","comfort"],
    ingredients: ["cauliflower","cheese","milk","butter","flour"], uses: "bake",
    steps: ["Blanch cauliflower florets 5 minutes; drain.", "Make a roux with butter and flour, whisk in milk and cheese.", "Pour over cauliflower and bake 25 minutes until golden."] },
  { id: "r28", name: "Cold Soba Salad", emoji: "🍥", minutes: 20, tags: ["vegan","no-cook"],
    ingredients: ["soba noodles","cucumber","carrot","soy sauce","sesame seeds","scallions"], uses: "chill & toss",
    steps: ["Cook soba, rinse cold.", "Julienne cucumber and carrot.", "Toss with soy sauce, sesame and scallions; chill."] },
  { id: "r29", name: "Corn & Potato Chowder", emoji: "🌽", minutes: 40, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["corn","potato","onion","milk","butter"], uses: "simmer",
    steps: ["Sweat onion in butter, add potato and milk.", "Simmer 20 minutes until potato is tender.", "Stir in corn, season, and serve."] },
  { id: "r30", name: "Beet & Feta Salad", emoji: "🫐", minutes: 20, tags: ["vegetarian","no-cook"],
    ingredients: ["beets","feta","arugula","walnuts","olive oil"], uses: "toss",
    steps: ["Slice cooked beets over a bed of arugula.", "Crumble feta, scatter walnuts.", "Dress with olive oil and serve."] },
  { id: "r31", name: "Chicken Noodle Soup", emoji: "🐔", minutes: 50, tags: ["family","freezer-friendly"],
    ingredients: ["chicken breast","noodles","carrot","celery","onion","chicken stock"], uses: "simmer",
    steps: ["Simmer chicken in stock with onion 25 minutes; shred.", "Add carrot, celery and noodles.", "Cook until tender; season and serve."] },
  { id: "r32", name: "Eggplant Parmigiana", emoji: "🍆", minutes: 60, tags: ["vegetarian","comfort"],
    ingredients: ["eggplant","tomato","mozzarella","parmesan","basil"], uses: "layer & bake",
    steps: ["Salt eggplant slices, rest, pat dry, then sear.", "Layer with tomato sauce, mozzarella and basil.", "Top with parmesan and bake 25 minutes."] },
  { id: "r33", name: "Turkey Wraps", emoji: "🌯", minutes: 12, tags: ["weeknight","no-cook"],
    ingredients: ["turkey slices","tortillas","lettuce","tomato","yogurt"], uses: "roll",
    steps: ["Warm the tortillas.", "Layer turkey, lettuce, tomato and a smear of yogurt.", "Roll tight and halve."] },
  { id: "r34", name: "Pea & Mint Soup", emoji: "🫛", minutes: 30, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["peas","mint","onion","vegetable stock","cream"], uses: "blend",
    steps: ["Sweat onion, add peas and stock; simmer 10 minutes.", "Blend with mint until vivid green.", "Swirl in cream and serve."] },
  { id: "r35", name: "Halloumi Couscous", emoji: "🧆", minutes: 25, tags: ["vegetarian","meal-prep"],
    ingredients: ["halloumi","couscous","cherry tomatoes","cucumber","lemon","olive oil"], uses: "sear & fluff",
    steps: ["Pour boiling water over couscous, cover 5 minutes, fluff.", "Sear halloumi slices until golden.", "Toss with tomatoes, cucumber, lemon and olive oil."] },
  { id: "r36", name: "Cinnamon Apple Crumble", emoji: "🍎", minutes: 45, tags: ["dessert","vegetarian"],
    ingredients: ["apple","flour","butter","oats","cinnamon","sugar"], uses: "bake",
    steps: ["Toss sliced apple with cinnamon and sugar in a dish.", "Rub flour, oats and butter into crumbs; scatter on top.", "Bake 30 minutes until bubbling and golden."] }
];

/* Seed pantry: qty in natural units; shelfDays converted to real dates on first load. */
const SEED_PANTRY = [
  { name: "Spinach",        qty: 200,  unit: "g",    shelfDays: 2,  category: "Produce" },
  { name: "Tomato",         qty: 6,    unit: "pcs",  shelfDays: 3,  category: "Produce" },
  { name: "Mushrooms",      qty: 300,  unit: "g",    shelfDays: 4,  category: "Produce" },
  { name: "Bell Pepper",    qty: 3,    unit: "pcs",  shelfDays: 6,  category: "Produce" },
  { name: "Zucchini",       qty: 2,    unit: "pcs",  shelfDays: 5,  category: "Produce" },
  { name: "Carrot",         qty: 500,  unit: "g",    shelfDays: 14, category: "Produce" },
  { name: "Broccoli",       qty: 1,    unit: "pcs",  shelfDays: 4,  category: "Produce" },
  { name: "Cucumber",       qty: 2,    unit: "pcs",  shelfDays: 7,  category: "Produce" },
  { name: "Banana",         qty: 5,    unit: "pcs",  shelfDays: 2,  category: "Produce" },
  { name: "Apple",          qty: 4,    unit: "pcs",  shelfDays: 12, category: "Produce" },
  { name: "Onion",          qty: 6,    unit: "pcs",  shelfDays: 21, category: "Produce" },
  { name: "Garlic",         qty: 1,    unit: "pack", shelfDays: 30, category: "Produce" },
  { name: "Eggs",           qty: 8,    unit: "pcs",  shelfDays: 9,  category: "Protein" },
  { name: "Chicken Breast", qty: 600,  unit: "g",    shelfDays: 2,  category: "Protein" },
  { name: "Tofu",           qty: 400,  unit: "g",    shelfDays: 5,  category: "Protein" },
  { name: "Chickpeas",      qty: 3,    unit: "pack", shelfDays: 300,category: "Pantry" },
  { name: "Red Lentils",    qty: 500,  unit: "g",    shelfDays: 365,category: "Pantry" },
  { name: "Rice",           qty: 1,    unit: "kg",   shelfDays: 400,category: "Pantry" },
  { name: "Pasta",          qty: 750,  unit: "g",    shelfDays: 400,category: "Pantry" },
  { name: "Black Beans",    qty: 2,    unit: "pack", shelfDays: 300,category: "Pantry" },
  { name: "Coconut Milk",   qty: 2,    unit: "pack", shelfDays: 200,category: "Pantry" },
  { name: "Soy Sauce",      qty: 250,  unit: "ml",   shelfDays: 500,category: "Pantry" },
  { name: "Olive Oil",      qty: 500,  unit: "ml",   shelfDays: 600,category: "Pantry" },
  { name: "Parmesan",       qty: 150,  unit: "g",    shelfDays: 25, category: "Dairy" },
  { name: "Feta",           qty: 200,  unit: "g",    shelfDays: 8,  category: "Dairy" },
  { name: "Mozzarella",     qty: 250,  unit: "g",    shelfDays: 6,  category: "Dairy" },
  { name: "Yogurt",         qty: 500,  unit: "g",    shelfDays: 5,  category: "Dairy" },
  { name: "Butter",         qty: 250,  unit: "g",    shelfDays: 40, category: "Dairy" },
  { name: "Milk",           qty: 1,    unit: "l",    shelfDays: 4,  category: "Dairy" }
];

/* Portions: how much of each ingredient one recipe (2 servings) consumes.
   Units match the seed pantry where names overlap, so pantry deduction is exact. */
const PORTIONS = {
  "apple": [2, "pcs"], "arborio rice": [200, "g"], "arugula": [100, "g"],
  "avocado": [1, "pcs"], "banana": [3, "pcs"], "basil": [10, "g"],
  "beans": [1, "pack"], "beef strips": [300, "g"], "beets": [2, "pcs"],
  "bell pepper": [2, "pcs"], "black beans": [1, "pack"], "bread": [4, "pcs"],
  "broccoli": [1, "pcs"], "butter": [30, "g"], "cabbage": [0.25, "pcs"],
  "carrot": [200, "g"], "cauliflower": [1, "pcs"], "celery": [2, "pcs"],
  "cheese": [100, "g"], "cherry tomatoes": [200, "g"], "chicken breast": [400, "g"],
  "chicken stock": [500, "ml"], "chickpeas": [1, "pack"], "cinnamon": [5, "g"],
  "coconut milk": [1, "pack"], "corn": [200, "g"], "couscous": [150, "g"],
  "cream": [100, "ml"], "cucumber": [1, "pcs"], "cumin": [5, "g"],
  "curry powder": [10, "g"], "dashi": [5, "g"], "dill": [5, "g"],
  "eggplant": [1, "pcs"], "eggs": [4, "pcs"], "feta": [100, "g"],
  "flour": [100, "g"], "garlic": [0.25, "pack"], "ginger": [20, "g"],
  "halloumi": [200, "g"], "honey": [30, "g"], "lemon": [1, "pcs"],
  "lettuce": [1, "pcs"], "lime": [1, "pcs"], "milk": [0.25, "l"],
  "mint": [10, "g"], "miso paste": [40, "g"], "mozzarella": [125, "g"],
  "mushrooms": [200, "g"], "noodles": [200, "g"], "oats": [100, "g"],
  "olive oil": [30, "ml"], "olives": [50, "g"], "onion": [2, "pcs"],
  "parmesan": [40, "g"], "pasta": [250, "g"], "peas": [150, "g"],
  "pork chops": [2, "pcs"], "potato": [400, "g"], "pumpkin": [400, "g"],
  "red lentils": [200, "g"], "red onion": [1, "pcs"], "rice": [0.25, "kg"],
  "rosemary": [5, "g"], "salmon": [300, "g"], "sausages": [4, "pcs"],
  "scallions": [3, "pcs"], "sesame seeds": [10, "g"], "shrimp": [250, "g"],
  "soba noodles": [200, "g"], "soy sauce": [30, "ml"], "spinach": [150, "g"],
  "sugar": [20, "g"], "thyme": [5, "g"], "tofu": [300, "g"],
  "tomato": [4, "pcs"], "tortillas": [4, "pcs"], "turkey slices": [150, "g"],
  "vegetable stock": [500, "ml"], "wakame": [10, "g"], "walnuts": [40, "g"],
  "white fish": [300, "g"], "whole chicken": [1, "pcs"], "yogurt": [200, "g"],
  "zucchini": [2, "pcs"]
};
function portionFor(ing) {
  const p = PORTIONS[ing];
  return p ? { qty: p[0], unit: p[1] } : { qty: 1, unit: "pcs" };
}
/* Unit conversion for pantry deduction (g<->kg, ml<->l). */
const UNIT_BASE = { "g": ["g", 1], "kg": ["g", 1000], "ml": ["ml", 1], "l": ["ml", 1000],
  "pcs": ["pcs", 1], "pack": ["pack", 1], "bunch": ["bunch", 1] };
function toBase(qty, unit) {
  const b = UNIT_BASE[unit];
  return b ? { qty: qty * b[1], unit: b[0] } : null;
}

/* Category lookup for consolidating shopping lists by aisle. */
const INGREDIENT_CATEGORIES = {
  "spinach":"Produce","tomato":"Produce","cherry tomatoes":"Produce","mushrooms":"Produce","bell pepper":"Produce",
  "zucchini":"Produce","carrot":"Produce","broccoli":"Produce","cucumber":"Produce","cabbage":"Produce",
  "banana":"Produce","apple":"Produce","onion":"Produce","red onion":"Produce","garlic":"Produce","ginger":"Produce",
  "basil":"Produce","mint":"Produce","dill":"Produce","arugula":"Produce","lettuce":"Produce","celery":"Produce",
  "cauliflower":"Produce","eggplant":"Produce","peas":"Produce","corn":"Produce","beets":"Produce","pumpkin":"Produce",
  "avocado":"Produce","lime":"Produce","lemon":"Produce","scallions":"Produce","olives":"Produce","potato":"Produce",
  "eggs":"Protein","chicken breast":"Protein","whole chicken":"Protein","beef strips":"Protein","pork chops":"Protein",
  "salmon":"Protein","white fish":"Protein","shrimp":"Protein","turkey slices":"Protein","sausages":"Protein",
  "tofu":"Protein","black beans":"Pantry","chickpeas":"Pantry","red lentils":"Pantry","beans":"Pantry",
  "rice":"Pantry","pasta":"Pantry","noodles":"Pantry","soba noodles":"Pantry","arborio rice":"Pantry","couscous":"Pantry",
  "oats":"Pantry","flour":"Pantry","tortillas":"Pantry","bread":"Bakery","miso paste":"Pantry","dashi":"Pantry",
  "wakame":"Pantry","sesame seeds":"Pantry","walnuts":"Pantry","sugar":"Pantry","honey":"Pantry",
  "coconut milk":"Pantry","soy sauce":"Pantry","olive oil":"Pantry","vegetable stock":"Pantry","chicken stock":"Pantry",
  "cumin":"Pantry","curry powder":"Pantry","cinnamon":"Pantry","thyme":"Pantry","rosemary":"Pantry",
  "parmesan":"Dairy","feta":"Dairy","mozzarella":"Dairy","cheese":"Dairy","halloumi":"Dairy","yogurt":"Dairy",
  "butter":"Dairy","milk":"Dairy","cream":"Dairy"
};
function categoryFor(ing) { return INGREDIENT_CATEGORIES[ing] || "Other"; }
