/* PantryPilot — local data: recipes + seed pantry.
   Ingredients use canonical lowercase names so tools can match pantry items reliably. */

const RECIPE_DB = [
  { id: "r01", name: "Garlicky Spinach Pasta", emoji: "🍝", minutes: 25, tags: ["vegetarian","comfort"],
    ingredients: ["spinach","pasta","garlic","olive oil","parmesan"], uses: "boil, wilt, toss" },
  { id: "r02", name: "Chicken Stir-Fry", emoji: "🥘", minutes: 30, tags: ["high-protein","weeknight"],
    ingredients: ["chicken breast","bell pepper","soy sauce","garlic","rice","carrot"], uses: "stir-fry" },
  { id: "r03", name: "Miso Soup with Tofu", emoji: "🍜", minutes: 15, tags: ["vegetarian","light"],
    ingredients: ["tofu","miso paste","scallions","wakame","dashi"], uses: "simmer" },
  { id: "r04", name: "Shakshuka", emoji: "🍳", minutes: 35, tags: ["vegetarian","brunch"],
    ingredients: ["eggs","tomato","bell pepper","onion","cumin","olive oil"], uses: "poach in sauce" },
  { id: "r05", name: "Salmon & Roast Veggies", emoji: "🐟", minutes: 40, tags: ["high-protein","omega-3"],
    ingredients: ["salmon","potato","broccoli","olive oil","lemon"], uses: "roast" },
  { id: "r06", name: "Mushroom Risotto", emoji: "🍚", minutes: 45, tags: ["vegetarian","comfort"],
    ingredients: ["mushrooms","arborio rice","onion","parmesan","butter"], uses: "slow stir" },
  { id: "r07", name: "Black Bean Tacos", emoji: "🌮", minutes: 20, tags: ["vegetarian","budget"],
    ingredients: ["black beans","tortillas","onion","avocado","lime","cumin"], uses: "warm & fold" },
  { id: "r08", name: "Greek Salad Bowl", emoji: "🥗", minutes: 15, tags: ["vegetarian","no-cook"],
    ingredients: ["cucumber","tomato","feta","red onion","olive oil","olives"], uses: "toss" },
  { id: "r09", name: "Beef & Broccoli Noodles", emoji: "🍖", minutes: 30, tags: ["high-protein"],
    ingredients: ["beef strips","broccoli","noodles","soy sauce","garlic","ginger"], uses: "stir-fry" },
  { id: "r10", name: "Pumpkin Soup", emoji: "🎃", minutes: 40, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["pumpkin","onion","carrot","vegetable stock","cream"], uses: "blend & simmer" },
  { id: "r11", name: "Egg Fried Rice", emoji: "🍙", minutes: 15, tags: ["budget","weeknight"],
    ingredients: ["eggs","rice","scallions","soy sauce","carrot","peas"], uses: "wok" },
  { id: "r12", name: "Caprese Sandwich", emoji: "🥪", minutes: 10, tags: ["vegetarian","no-cook"],
    ingredients: ["mozzarella","tomato","basil","bread","olive oil"], uses: "stack" },
  { id: "r13", name: "Lentil Dahl", emoji: "🍛", minutes: 45, tags: ["vegan","budget","freezer-friendly"],
    ingredients: ["red lentils","onion","tomato","ginger","cumin","coconut milk"], uses: "simmer" },
  { id: "r14", name: "Roast Chicken & Roots", emoji: "🍗", minutes: 70, tags: ["family","high-protein"],
    ingredients: ["whole chicken","potato","carrot","onion","rosemary","olive oil"], uses: "roast" },
  { id: "r15", name: "Shrimp Garlic Noodles", emoji: "🍤", minutes: 20, tags: ["high-protein","weeknight"],
    ingredients: ["shrimp","noodles","garlic","butter","scallions","lemon"], uses: "sauté" },
  { id: "r16", name: "Veggie Frittata", emoji: "🥚", minutes: 30, tags: ["vegetarian","clean-out-fridge"],
    ingredients: ["eggs","zucchini","bell pepper","onion","cheese"], uses: "bake" },
  { id: "r17", name: "Tomato Basil Bruschetta", emoji: "🍅", minutes: 15, tags: ["vegetarian","snack"],
    ingredients: ["tomato","basil","bread","garlic","olive oil"], uses: "toast & top" },
  { id: "r18", name: "Pork Chops & Apples", emoji: "🥩", minutes: 35, tags: ["family"],
    ingredients: ["pork chops","apple","onion","butter","thyme"], uses: "pan-sear" },
  { id: "r19", name: "Chickpea Curry", emoji: "🍲", minutes: 35, tags: ["vegan","budget","freezer-friendly"],
    ingredients: ["chickpeas","onion","tomato","curry powder","coconut milk","spinach"], uses: "simmer" },
  { id: "r20", name: "Zucchini Fritters", emoji: "🥒", minutes: 25, tags: ["vegetarian","clean-out-fridge"],
    ingredients: ["zucchini","eggs","flour","feta","dill"], uses: "pan-fry" },
  { id: "r21", name: "Minestrone", emoji: "🥣", minutes: 45, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["carrot","celery","tomato","beans","pasta","vegetable stock"], uses: "simmer" },
  { id: "r22", name: "Fish Tacos with Slaw", emoji: "🐟", minutes: 30, tags: ["weeknight"],
    ingredients: ["white fish","tortillas","cabbage","lime","avocado","yogurt"], uses: "sear & wrap" },
  { id: "r23", name: "Mushroom Toast", emoji: "🍄", minutes: 15, tags: ["vegetarian","snack"],
    ingredients: ["mushrooms","bread","butter","garlic","thyme"], uses: "sauté & pile" },
  { id: "r24", name: "Sheet-Pan Sausage & Peppers", emoji: "🌭", minutes: 40, tags: ["family","one-pan"],
    ingredients: ["sausages","bell pepper","onion","potato","olive oil"], uses: "roast" },
  { id: "r25", name: "Tofu Veggie Bowl", emoji: "🥡", minutes: 25, tags: ["vegan","meal-prep"],
    ingredients: ["tofu","rice","broccoli","carrot","soy sauce","sesame seeds"], uses: "assemble" },
  { id: "r26", name: "Banana Oat Pancakes", emoji: "🥞", minutes: 20, tags: ["breakfast","vegetarian"],
    ingredients: ["banana","oats","eggs","yogurt","honey"], uses: "blend & griddle" },
  { id: "r27", name: "Cauliflower Cheese Bake", emoji: "🧀", minutes: 50, tags: ["vegetarian","comfort"],
    ingredients: ["cauliflower","cheese","milk","butter","flour"], uses: "bake" },
  { id: "r28", name: "Cold Soba Salad", emoji: "🍥", minutes: 20, tags: ["vegan","no-cook"],
    ingredients: ["soba noodles","cucumber","carrot","soy sauce","sesame seeds","scallions"], uses: "chill & toss" },
  { id: "r29", name: "Corn & Potato Chowder", emoji: "🌽", minutes: 40, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["corn","potato","onion","milk","butter"], uses: "simmer" },
  { id: "r30", name: "Beet & Feta Salad", emoji: "🫐", minutes: 20, tags: ["vegetarian","no-cook"],
    ingredients: ["beets","feta","arugula","walnuts","olive oil"], uses: "toss" },
  { id: "r31", name: "Chicken Noodle Soup", emoji: "🐔", minutes: 50, tags: ["family","freezer-friendly"],
    ingredients: ["chicken breast","noodles","carrot","celery","onion","chicken stock"], uses: "simmer" },
  { id: "r32", name: "Eggplant Parmigiana", emoji: "🍆", minutes: 60, tags: ["vegetarian","comfort"],
    ingredients: ["eggplant","tomato","mozzarella","parmesan","basil"], uses: "layer & bake" },
  { id: "r33", name: "Turkey Wraps", emoji: "🌯", minutes: 12, tags: ["weeknight","no-cook"],
    ingredients: ["turkey slices","tortillas","lettuce","tomato","yogurt"], uses: "roll" },
  { id: "r34", name: "Pea & Mint Soup", emoji: "🫛", minutes: 30, tags: ["vegetarian","freezer-friendly"],
    ingredients: ["peas","mint","onion","vegetable stock","cream"], uses: "blend" },
  { id: "r35", name: "Halloumi Couscous", emoji: "🧆", minutes: 25, tags: ["vegetarian","meal-prep"],
    ingredients: ["halloumi","couscous","cherry tomatoes","cucumber","lemon","olive oil"], uses: "sear & fluff" },
  { id: "r36", name: "Cinnamon Apple Crumble", emoji: "🍎", minutes: 45, tags: ["dessert","vegetarian"],
    ingredients: ["apple","flour","butter","oats","cinnamon","sugar"], uses: "bake" }
];

/* Seed pantry: qty in natural units; shelfDays converted to real dates on first load. */
const SEED_PANTRY = [
  { name: "Spinach",        qty: 200,  unit: "g",    shelfDays: 2,  category: "Produce" },
  { name: "Tomato",         qty: 6,    unit: "pcs",  shelfDays: 3,  category: "Produce" },
  { name: "Mushrooms",      qty: 300,  unit: "g",    shelfDays: 4,  category: "Produce" },
  { name: "Bell Pepper",    qty: 3,    unit: "pcs",  shelfDays: 6,  category: "Produce" },
  { name: "Zucchini",       qty: 2,    unit: "pcs",  shelfDays: 5,  category: "Produce" },
  { name: "Carrot",         qty: 500,  unit: "g",    shelfDays: 14, category: "Produce" },
  { name: "Broccoli",       qty: 1,    unit: "pcs",  shelfDays: 4,  category: "Produce" },
  { name: "Cucumber",       qty: 2,    unit: "pcs",  shelfDays: 7,  category: "Produce" },
  { name: "Banana",         qty: 5,    unit: "pcs",  shelfDays: 2,  category: "Produce" },
  { name: "Apple",          qty: 4,    unit: "pcs",  shelfDays: 12, category: "Produce" },
  { name: "Onion",          qty: 6,    unit: "pcs",  shelfDays: 21, category: "Produce" },
  { name: "Garlic",         qty: 1,    unit: "pack", shelfDays: 30, category: "Produce" },
  { name: "Eggs",           qty: 8,    unit: "pcs",  shelfDays: 9,  category: "Protein" },
  { name: "Chicken Breast", qty: 600,  unit: "g",    shelfDays: 2,  category: "Protein" },
  { name: "Tofu",           qty: 400,  unit: "g",    shelfDays: 5,  category: "Protein" },
  { name: "Chickpeas",      qty: 3,    unit: "pack", shelfDays: 300,category: "Pantry" },
  { name: "Red Lentils",    qty: 500,  unit: "g",    shelfDays: 365,category: "Pantry" },
  { name: "Rice",           qty: 1,    unit: "kg",   shelfDays: 400,category: "Pantry" },
  { name: "Pasta",          qty: 750,  unit: "g",    shelfDays: 400,category: "Pantry" },
  { name: "Black Beans",    qty: 2,    unit: "pack", shelfDays: 300,category: "Pantry" },
  { name: "Coconut Milk",   qty: 2,    unit: "pack", shelfDays: 200,category: "Pantry" },
  { name: "Soy Sauce",      qty: 250,  unit: "ml",   shelfDays: 500,category: "Pantry" },
  { name: "Olive Oil",      qty: 500,  unit: "ml",   shelfDays: 600,category: "Pantry" },
  { name: "Parmesan",       qty: 150,  unit: "g",    shelfDays: 25, category: "Dairy" },
  { name: "Feta",           qty: 200,  unit: "g",    shelfDays: 8,  category: "Dairy" },
  { name: "Mozzarella",     qty: 250,  unit: "g",    shelfDays: 6,  category: "Dairy" },
  { name: "Yogurt",         qty: 500,  unit: "g",    shelfDays: 5,  category: "Dairy" },
  { name: "Butter",         qty: 250,  unit: "g",    shelfDays: 40, category: "Dairy" },
  { name: "Milk",           qty: 1,    unit: "l",    shelfDays: 4,  category: "Dairy" }
];

/* Category lookup for consolidating shopping lists by aisle. */
const INGREDIENT_CATEGORIES = {
  "spinach":"Produce","tomato":"Produce","cherry tomatoes":"Produce","mushrooms":"Produce","bell pepper":"Produce",
  "zucchini":"Produce","carrot":"Produce","broccoli":"Produce","cucumber":"Produce","cabbage":"Produce",
  "banana":"Produce","apple":"Produce","onion":"Produce","red onion":"Produce","garlic":"Produce","ginger":"Produce",
  "basil":"Produce","mint":"Produce","dill":"Produce","arugula":"Produce","lettuce":"Produce","celery":"Produce",
  "cauliflower":"Produce","eggplant":"Produce","peas":"Produce","corn":"Produce","beets":"Produce","pumpkin":"Produce",
  "avocado":"Produce","lime":"Produce","lemon":"Produce","scallions":"Produce","olives":"Produce","potato":"Produce",
  "eggs":"Protein","chicken breast":"Protein","whole chicken":"Protein","beef strips":"Protein","pork chops":"Protein",
  "salmon":"Protein","white fish":"Protein","shrimp":"Protein","turkey slices":"Protein","sausages":"Protein",
  "tofu":"Protein","black beans":"Pantry","chickpeas":"Pantry","red lentils":"Pantry","beans":"Pantry",
  "rice":"Pantry","pasta":"Pantry","noodles":"Pantry","soba noodles":"Pantry","arborio rice":"Pantry","couscous":"Pantry",
  "oats":"Pantry","flour":"Pantry","tortillas":"Pantry","bread":"Bakery","miso paste":"Pantry","dashi":"Pantry",
  "wakame":"Pantry","sesame seeds":"Pantry","walnuts":"Pantry","sugar":"Pantry","honey":"Pantry",
  "coconut milk":"Pantry","soy sauce":"Pantry","olive oil":"Pantry","vegetable stock":"Pantry","chicken stock":"Pantry",
  "cumin":"Pantry","curry powder":"Pantry","cinnamon":"Pantry","thyme":"Pantry","rosemary":"Pantry",
  "parmesan":"Dairy","feta":"Dairy","mozzarella":"Dairy","cheese":"Dairy","halloumi":"Dairy","yogurt":"Dairy",
  "butter":"Dairy","milk":"Dairy","cream":"Dairy"
};
function categoryFor(ing) { return INGREDIENT_CATEGORIES[ing] || "Other"; }
